- name: AoC-badges
  # You may pin to the exact commit or the version.
  # uses: J0B10/aoc-badges-action@75cd611df531bd9aa0675cae13be418d73cbdf76
  uses: J0B10/aoc-badges-action@v3.0.0
  with:
    # Your session code for login. Retrive it from your browser cookies. Make sure you use a secret to not leak this to public.

    session:${{ secrets.AOC_SID }} 
    # Your unique userid on adventofcode.com, obtain it from **YOUR** private leaderboard url (its the number at the end of the url).

    userid:2565149 
    # The year for which the stats should be retrived.  If not speified, the current year (from system time) is used.

    year: # optional
    # The url of your leaderboard json file.  You can get it by just appending .json to the url of your leaderboard.

    leaderboard: # optional
    # The file where the badges should be updated. Default is README.md

    file: # optional, default is README.md
    # A regular expression to find the day badge in your file. Must be changed if you change the badge.

    dayRegex: # optional, default is (?<=https:\/\/img\.shields\.io\/badge\/day%20ðŸ“…-)[0-9]+(?=-blue)
    # A regular expression to find the stars badge in your file. Must be changed if you change the badge.

    starsRegex: # optional, default is (?<=https:\/\/img\.shields\.io\/badge\/stars%20â­-)[0-9]+(?=-yellow)
    # A regular expression to find the completed days badge in your file. Must be changed if you change the badge.

    daysCompletedRegex: # optional, default is (?<=https:\/\/img\.shields\.io\/badge\/days%20completed-)[0-9]+(?=-red)
